FROM grafana/grafana-arm32v7-linux:6.2.5

COPY LICENSE                          /linkerd/LICENSE
COPY grafana/dashboards               /var/lib/grafana/dashboards
COPY grafana/dashboards/top-line.json /usr/share/grafana/public/dashboards/home.json
